language: python
python:
  - "3.7"
dist: xenial
addons:
  apt:
    packages:
      - clang
      - gcc
      - blender
      - xz-utils

before_install:
  # install cython
  - pip install -q cython

install:
  # manually install recent blender off mirror
  - export BLENDER_VERSION=2.83
  - export BLENDER_BUGFIX_VERSION=15
  - echo "Installing Blender ${BLENDER_VERSION}"
  - export BNAME="blender-${BLENDER_VERSION}.${BLENDER_BUGFIX_VERSION}-linux64"
  - wget "https://blender.org/download/Blender${BLENDER_VERSION}/${BNAME}.tar.xz"
  - tar -xf ${BNAME}.tar.xz

  # set up path to use this blender
  - export PATH=${PWD}/${BNAME}:${PATH}

  # register addon
  - export BLENDER_DIR=${HOME}/.config/blender/${BLENDER_VERSION}
  - mkdir -p ${BLENDER_DIR}/scripts/addons
  - "echo \" { \\\"Copy Target\\\" : \\\"${BLENDER_DIR}/scripts/addons\\\" }\" > conf.json"
  - python setup.py build --copy

script: ./run_test.sh -b ${BNAME}/blender
